apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: music
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
    - name: {{ .Values.container.name }}
      image: {{ .Values.container.image }}
      ports:
        - containerPort: 8080

