kind: Service     
apiVersion: v1     
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: music    
  type: {{ .Values.serviceType | default "NodePort" }}
  ports:         
  - name: http   
    protocol: {{ .Values.ports.protocol }}
    port: {{ .Values.ports.port }}
    targetPort: {{ .Values.ports.targetPort }}
