database_prod: 
  dbname: db_mysql
  dbtable: music
database_test: 
  dbname: db_mysql-test
  dbtable: music
pods: 
  image: spring-music
  repo: yanivomc
  tag: latest
food:
  drink: beer
  eat: Peanut Butter and Jelly sandwich
