apiVersion: apps/v1
kind: Deployment
metadata:
  name: besteffort
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-music
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
      - name: spring-music
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
        # besteffort if no resources specified
        #resources:
        #    requests:
        #      memory: 256Mi
        #      cpu: 100m