apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: spring
    tier: fe
spec:
  replicas: 2
  selector:  
    matchLabels:
      tier: frontend
  template: 
    metadata:
      labels:
        tier: frontend
  spec:      
    containers:
    - name: bear-app
      image: supergiantkir/animals:bear
      volumeMounts:
      - name: app-storage
        mountPath: /storage
    - name: spring-music
      image: yanivomc/spring-music:latest
      volumeMounts:
      - name: app-storage
        mountPath: /storage
    volumes:
      - name: app-storage  
        hostPath:
        path:  /storage
        type: DirectoryOrCreate

 


