version: '3.8'
services:
  spring-app:
    image: liran/spring-music:1
    restart: always
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - ./volume_app:/code
    networks:
      - db_layer
      - app_layer

  mysql:
    image: yanivomc/spring-mysql:latest
    volumes:
      - ./artifacts:/var/log
    networks:
      - db_layer

networks:
  db_layer:
  app_layer:
