kind: Service     
apiVersion: v1     
metadata:
  name: {{ .Release.Name }}-service
  labels:
  {{- include "spring.labels" . | indent 5 }}
spec:
  selector:
    {{- include "spring.labels" . | indent 5 }}
  type: NodePort
  ports:         
  - name: http   
    protocol: TCP
    port: 80
    targetPort: 8080
