apiVersion: apps/v1
kind: Deployment
metadata:
<<<<<<< HEAD
  name: spring-music
=======
  name: spring-deployment
>>>>>>> 8f0c7ede6adc9b2a2ff9e340d38590854a6848b5
spec:
  replicas: 2
  selector:
    matchLabels:
<<<<<<< HEAD
      app: spring-music
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
        - name: spring-music
          image: yanivomc/spring-music:latest
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: spring-music
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: spring-music
=======
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
>>>>>>> 8f0c7ede6adc9b2a2ff9e340d38590854a6848b5
