apiVersion: apps/v1
kind: Deployment
metadata:
  name: may
spec:
  replicas: 3
  selector:  
    matchLabels:
      tier: storage
  template:   
    metadata:
      labels:
        tier: storage
    spec:
      containers:
      - name: app1
        image: supergiantkir/animals:bear
        volumeMounts:
        - name: app-storage
          mountPath: /storage
      - name: app2
        image: yanivomc/spring-music:latest
        volumeMounts:
        - name: app-storage
          mountPath: /storage
      volumes:
      - name: app-storage
        hostPath:
          # directory location on host
          path: /tmp/files
          # this field is optional
          type: Directory

      


