apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  selector: 
    matchLabels:
      app: music  
  replicas: {{ .Values.deployment.replicas }}  
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: {{ .Values.containers.name }}
        image: {{ .Values.containers.name }}
        ports:
        - containerPort: 8080
