kind: Service     
apiVersion: v1     
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: music    
  type: {{ .Values.serviceType | default "NodePort" }}
  ports:         
  - name: http   
    protocol: TCP
    port: 80
    targetPort: 8080
