version: '3.8' # docker compose yml version for docker compose builder
networks: # Define netwroks per service / role
  db-lan:
  fe-app:
services: # Here we define our architecture services / roles
  spring-app: # or web_role  , api_role , db_mysql , db_redis ....
    image: yanivomc/spring-music:latest # docker run -d yanivomc/spring-app:2.1
    networks: # custom configuration per network defined
      - fe-app
      - db-lan
    ports: # Ports we wish to expose source:target
      - 80:8080
    command: java -jar -Dspring.profiles.active=mysql spring-music.jar
    # env_file:
    #   - ./env-prod
  mysql-db:
    # build:  # Dockerfile to build or use image: to pull from DockerHub (public/private) or git
    #   context: ./dockerfiles # folder where the dockerfile is located
    #   dockerfile: Dockerfile-debug #[dockerfile-name]
    container_name: db_mysql
    image: yanivomc/spring-mysql:latest # docker run -d yanivomc/mysql-db:2.1
    networks: # custom configuration per network defined
      - db-lan
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=music
#   Image: yanivomc/spring-music:latest
#   ports: # Ports we wish to expose source:target
#     - 8080:8080
#     - 80:80
#   volumes: # Which Bind mounts or Volumes to mount source:target
#     - type: bind        # Shortsyntax -> ./source:/code
#       source: /source
#       target: /code
#     - type: volume       # Shortsyntax -> logicalVolume01:/var/log
#       source: logicalVoloume01
#       target: /var/log
# volumes:
#   logicalVoloume01: