apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hostbased

spec:
  ingressClassName: nginx
  rules:
  # change the IP below based on the DNS resolution of your LB (under kubectl get svc -n ingress-nginx)
  - host: bear.52.31.3.201.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
             name: bear-svc
             port:
                number: 80
  - host: moose.52.31.3.201.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
             name: moose-svc
             port:
                number: 80              
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: animals

spec:
  ingressClassName: nginx
  rules:
  - host: animals-52.31.3.201.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
             name: moose-svc
             port:
                number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
             name: bear-svc
             port:
                number: 80         
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-animals

spec:
  ingressClassName: nginx
  rules:
  - host: my-animals.52.31.3.201.nip.io
    http:
      paths:
      - path: /moose(/|$)(.*)
        pathType: Prefix
        backend:
          service:
             name: moose-svc
             port:
                number: 80
      - path: /bear(/|$)(.*)
        pathType: Prefix
        backend:
          service:
             name: bear-svc
             port:
                number: 80                                                    