apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
spec:
  containers:
  - image: supergiantkir/animals:bear
    name: bear
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"