apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: bears
    image: supergiantkir/animals:bear
    volumeMounts:
    - name: app-storage
      mountPath: /storage
  - name: spring
    image: yanivomc/spring-music:latest
    volumeMounts:
    - name: app-storage
      mountPath: /storage
  volumes:
  - name: app-storage
    hostPath:
      path: /tmp/files
      type: DirectoryOrCreate
