apiVersion: v1
kind: Pod
metadata:
  name: burstable-pod
spec:
  containers:
  - name: burstable-container
    image: busybox
    command: ["/bin/sleep", "3600"]
    resources:
      requests:
        memory: "10Mi"
        cpu: "100m"
      limits:
        memory: "20Mi"
        cpu: "200m"

