apiVersion: v1
kind: Pod
metadata:
  name: guaranteed-pod
spec:
  containers:
  - name: guaranteed-container
    image: busybox
    command: ["/bin/sleep", "3600"]
    resources:
      requests:
        memory: "20Mi"
        cpu: "200m"
      limits:
        memory: "20Mi"
        cpu: "200m"

