apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
  namespace: k8s-ops
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       — name: nginx
         image: nginx
          ports:
           —containerPort: 80