apiVersion: apps/v1
kind: Deployment
metadata:
  name: moose-dpl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moose
  template:
    metadata:
      labels:
        app: moose
    spec:
      containers:
        - name: moose
          image: supergiantkir/animals:moose
          ports:
            - containerPort: 80
