version: '3' 
services: 
  web: 
   build: ./roles/web/
   image: yanivomc/jb-elbit:1.0
   ports: 
     - 8081:8080
   networks: 
     - app_layer
     - db_layer


  web-backup: 
   image: yanivomc/jb-elbit:1.1
   ports: 
     - 8082:8080
   networks: 
     - app_layer
     - db_layer

  
  
  db_mysql:
    image: wangxian/alpine-mysql
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=music
    ports:
      - 3302:3306
    networks:
      - db_layer
    volumes: 
      - logicalVoloume01:/app



networks: 
 db_layer:
  driver: bridge
 app_layer:
  driver: bridge

volumes:
 logicalVoloume01: