apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear-deployment
  labels:
    app: bear
    type: animal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: bear-container
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
