version: "3.2"
services:
####################################
# CODE SERVER service A
####################################
  codeserver-a-fe:
    container_name: code-server-a
    image:   lscr.io/linuxserver/code-server:latest
    environment:
        - PUID=0 
        - PGID=0 
        - PASSWORD=password 
    privileged: true
    # volumes_from:
    #   - dockersock:/var/run/
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - dockersock:/var/run/
    # depends_on:
    #   - cloudframeworklabs-dapr
    restart: always
    ports:
        - 90:8443
    networks:
        - cloudframework

####################################
# DIND Side car for CODE SERVER A
####################################
  cloudframeworklabs-dapr:
    container_name: cloudframeworklabs-dapr
    image: "docker:23.0.1-dind-alpine3.17"
    depends_on:
      - codeserver-a-fe
    volumes:
      - dockersock:/var/run/
    network_mode: "container:code-server-a"  
    privileged: true
    networks:
        - cloudframework



####################################
# CODE SERVER service B
####################################
  codeserver-b-fe:
    container_name: code-server-b
    image:   lscr.io/linuxserver/code-server:latest
    environment:
        - PUID=0 
        - PGID=0 
        - PASSWORD=password 
    privileged: true
    # volumes_from:
    #   - dockersock:/var/run/
    volumes:
      - /usr/bin/docker:/usr/bin/docker
      - dockersock-b:/var/run/
    # depends_on:
    #   - cloudframeworklabs-dapr
    restart: always
    ports:
        - 91:8443
    networks:
        - cloudframework

####################################
# DIND Side car for CODE SERVER A
####################################
  cloudframeworklabs-dapr-b:
    container_name: cloudframeworklabs-dapr-b
    image: "docker:23.0.1-dind-alpine3.17"
    depends_on:
      - codeserver-b-fe
    volumes:
      - dockersock-b:/var/run/
    network_mode: "container:code-server-b"  
    privileged: true
    networks:
        - cloudframework

networks:
  # rabbitmq_go_net:
  #   driver: bridge
  cloudframework:
    driver: bridge
volumes:
  dockersock:
  dockersock-b:
  

