apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  storageClassName: slow-io
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: pvc-2d43e150-ed26-4c14-8431-6a3ea46d9503
    fsType: ext4

