version: "3.8"

networks:
  db-lan:
  fe-lan:

services:
  spring-app:
    image: yanivomc/spring-music:latest
    ports:
      - 80:8080
    networks:
      - db-lan
      - fe-lan
  mysql-db:
    image: yanivomc/spring-mysql:latest
    networks:
      - db-lan


