version: "3.8"

networks:
  db-lan:
  fe-lan:

services:
  spring-app:
    image: yanivomc/spring-music:latest
    ports:
      - 80:8080
    networks:
      - db-lan
      - fe-lan
    command: java -jar -Dspring.profiles.active=mysql spring-music.jar

  mysql-db:
    image: yanivomc/spring-mysql:latest
    container_name: db_mysql
    networks:
      - db-lan
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes 
      - MYSQL_DATABASE=music


