apiVersion: v1
kind: Pod
metadata:
  name: qos-burstable
  namespace: qos-example
spec:
  containers:
  - name: qos-demo-ctr2
    image: nginx
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"