apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fe  
  name: redis
spec:
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
  replicas: 5
  selector:
    matchLabels:
      yaniv: fe-v1
  template:
    metadata:
      labels:
        yaniv: fe-v1
    spec:
      containers:
      - name: redis
        image: supergiantkir/animals:bear
        volumeMounts:
        - name: hostpathvolume
          mountPath: /storage
      - name: springapp
        image: yanivomc/spring-music:latest
        volumeMounts:
        - name: hostpathvolume
          mountPath: /sotrage
      volumes:
      - name: hostpathvolume
        hostPath:
          path: /data



