apiVersion: apps/v1
kind: Deployment
metadata:
  name: moose
spec:
  replicas: 2
  selector:
    matchLabels:
      app: animals
      animal: moose
  template:
    metadata:
      labels:
        app: animals
        animal: moose
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: animal
                operator: In
                values:
                - bear
            topologyKey: topology.kubernetes.io/zone
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: animal
                operator: In
                values:
                - moose
            topologyKey: "topology.kubernetes.io/zone"

      containers:
        - name: moose
          image: supergiantkir/animals:moose
          ports:
            - containerPort: 80
