apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spring-music #from RELEASE NAME
spec:
  selector: 
    matchLabels:
      app: music  
  replicas: {{ .Values.release.replicas }}
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: {{ .Release.Name }}spring-music #from values
        image: {{ .Values.release.image }}:{{ .Values.release.tag }}
        ports:
        - containerPort: {{ .Values.release.targetPort }}

