apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
  labels: 
    application: music
    stage: dev
spec:
  selector:
    matchLabels:
      type: music-app
  replicas: 3 
  template: 
    metadata:
      labels:
        type: music-app
    spec:
      containers:
      - name: music-app
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
