version: 2.1

orbs:
  maven: circleci/maven@2.0.0  # Maven orb for building and testing Java projects

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0  # Java build environment
    steps:
      - checkout
      - run:
          name: Build the Project
          command: cd code/nexus-lab/circleci-101 && mvn clean package spring-boot:repackage

  lint:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Lint the Code
          app_src_directory: ./code/nexus-lab/circleci-101
          command: cd code/nexus-lab/circleci-101 && mvn checkstyle:check

  # unit_test:
  #   docker:
  #     - image: cimg/openjdk:11.0
  #   steps:
  #     - checkout
  #     - run:
  #         name: Run Unit Tests
  #         command: cd code/nexus-lab/circleci-101 && mvn test

  unit_test:
    docker:
    - image: cimg/openjdk:11.0
    steps:
      - checkout
      - maven/test:
          name: Run Unit Tests
          app_src_directory: ./code/nexus-lab/circleci-101

  deploy_mock:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
          name: Mock Deployment
          command: echo "Deployment complete."

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - unit_test:
          requires:
            - build
      - deploy_mock:
          requires:
            - lint
            - unit_test