version: 2.1

orbs:
  slack: circleci/slack@4.9.3

jobs:
  mock-build:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Mock Build Step
          command: |
            echo "Starting the mock build..."
            sleep 5
            echo "Build complete."

workflows:
  build-and-notify:
    jobs:
      - mock-build
      - slack/notify:
          requires:
            - mock-build
          event: pass
          template: basic_success_1
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Mock Build Completed Successfully*"
                  }
                }
              ]
            }
