version: 2.1

orbs:
  maven: circleci/maven@2.0.0  # Maven orb for Java build and tests
  node: circleci/node@4.7.0    # JavaScript linting orb

jobs:
  build:
    executor:
      name: maven/default
    steps:
      - checkout
      - maven/with-cache:  # Using the Maven orb to cache dependencies
          steps:
            - maven/compile

  lint:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Lint the Code
          command: cd code/nexus-lab/circleci-101 && mvn checkstyle:check

  unit_test:
    executor:
      name: maven/default
    steps:
      - checkout
      - maven/test  # Using the Maven orb for running unit tests

  deploy_mock:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
          name: Mock Deployment
          command: echo "Deployment complete."

  node_lint:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Lint JavaScript Code
          command: |
            cd code/nexus-lab/circleci-101
            npm install
            npm run lint

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - node_lint:
          requires:
            - build
      - lint:
          requires:
            - build
      - unit_test:
          requires:
            - build
      - deploy_mock:
          requires:
            - lint
            - unit_test
