version: 2.1

orbs:
  maven: circleci/maven@3.0.0  # Maven orb for Java build and tests

jobs:
  build:
    executor:
      name: maven/default
    steps:
      - checkout
      - maven/install-deps:
          working_directory: code/nexus-lab/circleci-101
      - maven/test:
          working_directory: code/nexus-lab/circleci-101
      - run:
          name: Package the Application
          command: mvn clean package spring-boot:repackage
          working_directory: code/nexus-lab/circleci-101

  lint:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Lint the Code
          command: cd code/nexus-lab/circleci-101 && mvn checkstyle:check

  unit_test:
    executor:
      name: maven/default
    steps:
      - checkout
      - maven/test:
          working_directory: code/nexus-lab/circleci-101

  deploy_mock:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
          name: Mock Deployment
          command: echo "Deployment complete."

  node_lint:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - run:
          name: Lint JavaScript Code
          command: |
            cd code/nexus-lab/circleci-101
            npm install
            npm run lint

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - node_lint:
          requires:
            - build
      - lint:
          requires:
            - build
      - unit_test:
          requires:
            - build
      - deploy_mock:
          requires:
            - lint
            - unit_test
