version: 2.1

orbs:
  slack: circleci/slack@4.9.3
  docker: circleci/docker@2.8.1

parameters:
  node_versions:
    type: array
    default: ["14", "16", "18"]
  test_cases:
    type: array
    default: ["unit", "integration", "e2e"]

jobs:
  checkout-code:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

  lint:
    docker:
      - image: circleci/node:<< parameters.node_version >>
    parameters:
      node_version:
        type: string
    steps:
      - checkout
      - run:
          name: Lint Code
          command: |
            echo "Mock: Linting code for Node.js version << parameters.node_version >>..."
            sleep 2
            echo "Linting completed."

  build:
    docker:
      - image: circleci/node:<< parameters.node_version >>
    parameters:
      node_version:
        type: string
    steps:
      - checkout
      - run:
          name: Build Application
          command: |
            echo "Mock: Building application for Node.js version << parameters.node_version >>..."
            sleep 2
            echo "Build completed."

  test:
    docker:
      - image: circleci/node:<< parameters.node_version >>
    parameters:
      node_version:
        type: string
      test_case:
        type: string
    steps:
      - checkout
      - run:
          name: Run Test Case
          command: |
            echo "Mock: Running << parameters.test_case >> tests for Node.js version << parameters.node_version >>..."
            sleep 2
            echo "Tests completed."

  security-test:
    docker:
      - image: circleci/node:<< parameters.node_version >>
    parameters:
      node_version:
        type: string
    steps:
      - checkout
      - run:
          name: Run Security Tests
          command: |
            echo "Mock: Running security tests for Node.js version << parameters.node_version >>..."
            sleep 2
            echo "Security tests completed."

  build-and-push:
    executor: docker/docker
    parameters:
      node_version:
        type: string
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: yanivomc/orb-test:<< parameters.node_version >>-<< pipeline.git.branch >>
          extra_build_args:
            NODE_VERSION: << parameters.node_version >>
          path: ./code/nexus-lab/circleci-101/solutions/lab102/end2end
      - docker/push:
          image: yanivomc/orb-test:<< parameters.node_version >>-<< pipeline.git.branch >>
      - slack/notify:
          event: pass
          template: basic_success_1
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Docker Image Build and Push Completed Successfully for Node.js version << parameters.node_version >>*"
                  }
                }
              ]
            }

workflows:
  version: 2
  complex-pipeline:
    jobs:
      - checkout-code
      - lint:
          matrix:
            parameters:
              node_version: << pipeline.parameters.node_versions >>
          requires:
            - checkout-code
      - build:
          matrix:
            parameters:
              node_version: << pipeline.parameters.node_versions >>
          requires:
            - lint
      - test:
          matrix:
            parameters:
              node_version: << pipeline.parameters.node_versions >>
              test_case: << pipeline.parameters.test_cases >>
          requires:
            - build
      - security-test:
          matrix:
            parameters:
              node_version: << pipeline.parameters.node_versions >>
          requires:
            - build
      - build-and-push:
          matrix:
            parameters:
              node_version: << pipeline.parameters.node_versions >>
          requires:
            - test
            - security-test
          filters:
            branches:
              only: workshop/circleci
