# Lab Option 2: Advanced Level

version: 2.1

orbs:
  slack: circleci/slack@4.5.0

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Mock Build Step
          command: |
            echo "Starting the mock build..."
            sleep 10
            echo "Build complete."

workflows:
  version: 2
  simple-build-notify:
    jobs:
      - build
      - slack/notify:
          requires:
            - build
          template: basic_success_1
          attachments: |
            [{
              "color": "#36a64f",
              "text": "Build completed successfully for $CIRCLE_PROJECT_REPONAME on branch $CIRCLE_BRANCH"
            }]