apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-2
  namespace: qos-example-burst
spec:
  containers:
  - name: qos-demo-2-ctr
    image: supergiantkir/animals:bear
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"