apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
  namespace: qos-example-gur
spec:
  containers:
  - name: qos-demo-ctr
    image: supergiantkir/animals:bear
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"