version: '3.8' # docker compose yml version for docker compose builder
services: # Here we define our architecture services / roles
  nginx: # or web_role  , api_role , db_mysql , db_redis ....
    build: .
    image: yanivomc/nginx:latest
    ports: # Ports we wish to expose source:target
      - 8080:8080
      - 80:80
    networks:
      - mylan
    volumes:
      - myvolume:/codenginx
    entrypoint: entrypoint"
  
  spring-app:
    image: yanivomc/spring-music:latest
    ports:
      - 8081:8080
    networks:
      - mylan
      - dmz
    volumes:
      - myvolume:/code:ro
      - /tmp/code:/mnt/files


networks:
  mylan:
  dmz:

volumes:
  myvolume: