apiVersion: v1
kind: Pod
metadata:
  name: qos-guar-pod
spec:
  containers:
  - name: qos-guar-spod
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"