kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: development
  name: ingress-reader
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-reader-binding
  namespace: development
subjects:
- kind: ServiceAccount
  name: ingress-user
  namespace: default
roleRef:
  kind: Role
  name: ingress-reader
  apiGroup: rbac.authorization.k8s.io
