version: "3.9"

networks:
 db-lan:
 fe-lan:

services:
 spring-app:
  image: yanivomc/spring-music:latest
  command: java -jar -Dspring.profiles.active=mysql spring-music.jar
  volumes:
   - ./data:/mydata
  ports:
   - "80:8080"
  networks:
   - db-lan
   - fe-lan

 mysql-db: # ROLE NAME
   image: yanivomc/spring-mysql:latest
   container_name: mysql_db
   environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes 
      - MYSQL_DATABASE=music
   networks:
     - db-lan
   volumes:
     - ./data:/yourdata


