apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-app
spec:
  selector:
    matchLabels:
      app: music
  replicas: 3 
  template: 
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: music
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
