version: '1.1'

networks:
  db-lan:
  fe-lan:

services:
  spring-app:
    image: yanivomc/spring-music:latest
    command: java -jar -Dspring.profiles.active=mysql spring-music.jar
    networks:
      - fe-lan
      - db-lan
    ports:
      - 80:8080

  mysql-db:
    image: yanivomc/spring-mysql:latest
    container_name: db_mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=music
    networks:
      - db-lan