version: '1.0'

networks:
  db-lan:
  fe-lan:

services:
  spring-app:
    image: yanivomc/spring-music:latest
    networks:
      - fe-lan
      - db-lan
    ports:
      - 80:8080

  mysql-db:
    image: yanivomc/spring-mysql:latest
    networks:
      - db-lan