version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0  # Java build environment
    steps:
      - checkout
      - run:
          name: Build the Project
          command: cd code/nexus-lab/circleci-101 && mvn clean package spring-boot:repackage

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build