# K8S Deployment filr for FE
# This file is used to deploy the FE application in K8S cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jb-platform-fe
  # namespace: jb-platform
  labels:
    app: jb-platform-fe
spec:
  selector:
    matchLabels:
      app: jb-platform-fe
  replicas: 3
  template:
    metadata:
      labels:
        app: jb-platform-fe
    spec:
      containers:
      - name: jb-platform-fe
        image: yanivomc/jb-elearning-fe:v1.0.2.8-sec-fixed
        imagePullPolicy: Always
        ports:
        - containerPort: 9003
        env:
          - name:  AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name:  jb-platform-entrypoint-secret
                key:  key
          - name:  AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name:  jb-platform-entrypoint-secret
                key:  secret
        # command:
        #   - "sleep"
        #   - "60000"
      - name: jb-platform-fe-sidecar
        image: yanivomc/jb-elearning-dapr:v1.0.1.5
        imagePullPolicy: Always
        command: ["./daprd"]
        args: ["-app-id" ,"jb-platform-fe-prod", "-placement-host-address", "jb-platform-placement:50006", "-components-path", "/components", "-log-level", "debug"]