# AWS Credintials k8s //kubectl create secret docker-registry NAME --docker-username=user --docker-password=password --docker-email=email [--docker-server=string] [--from-literal=key1=value1] [--dry-run] 
apiVersion: v1
kind: Secret
metadata:
  name: jb-platform-entrypoint-secret
type: Opaque
stringData:
  key: "AKIAI5QIA4TLWWBJA6CQ"
  secret: "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"

