apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bear-app
  template:
    metadata:
      labels:
        svc_lb: animals
        app: bear-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: system
                operator: In
                values: ["linux"]
      containers:
      - image: supergiantkir/animals:bear
        imagePullPolicy: Always
        name: bear
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      restartPolicy: Always
