version: '3.4'
services:
  fe-nft: 
    image: yanivomc/fe-nft:latest
    build: ./part-2-fe
    networks:
      - cloudframework
    depends_on:
      - product-consumer
  
  product-consumer:
    image: yanivomc/product-consumer-nft:latest
    build: ./part-3-product-consumer
    networks:
      - cloudframework
    depends_on:
      - rmq
      - mongo
      # - myqsl

############################
  # RMQ - queue layer
############################
  rmq:
    image: 504949722475.dkr.ecr.eu-west-1.amazonaws.com/cf-be:rmq-1.0
    restart: always
    container_name: 'rmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - cloudframework
############################
  # MYQSL state store 
############################



############################
  # Mongodb state store
############################
  mongo:
    image: "mongo"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=pass12345
    ports:
      - "27017:27017"
    networks:
      - cloudframework
    volumes:
      - mongodb:/data/db
############################
  # Mongodb express UI
############################
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongo
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
    - ME_CONFIG_BASICAUTH_USERNAME=admin
    - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
    - mongo
    networks:
    - cloudframework
    ports:
    - 8081:8081


networks:
  cloudframework:
    driver: bridge

volumes:
  cf_data:
  mongodb:
  mongodb-express: