version: '3.4'
services:
  fe-nft: 
    image: yanivomc/fe-nft:latest
    build: ./part-2-fe
    networks:
      - cloudframework
    depends_on:
      - product-consumer
      - rmq
      - mongo
    ports:
      - "8080:8081"
    restart: always
  
  product-consumer:
    image: yanivomc/product-consumer-nft:latest
    build: ./part-3-product-consumer
    networks:
      - cloudframework
    restart: always
    depends_on:
      - rmq
      - mongo
      # - myqsl
  
  consumer-mv:
    image: yanivomc/consumer-mv-nft:latest
    build: ./part-4-mv-consumer
    networks:
      - cloudframework
    restart: always
    depends_on:
      - rmq
      - mongo

############################
  # RMQ - queue layer
############################
  rmq:
    image: yanivomc/nft-rmq:latest
    restart: always
    container_name: 'rmq'
    ports:
        - 5672:5672
        - 15672:15672
    
    networks:
        - cloudframework
############################
  # MYQSL state store 
############################



############################
  # Mongodb state store
############################
  mongo:
    image: "mongo"
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=pass12345
    ports:
      - "27017:27017"
    networks:
      - cloudframework
    volumes:
      - mongodb:/data/db
    restart: always
############################
  # Mongodb express UI
############################
  mongo-express:
    image: mongo-express
    
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongo
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
    - ME_CONFIG_BASICAUTH_USERNAME=admin
    - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
    - mongo
    networks:
    - cloudframework
    ports:
    - 9091:8081
    restart: always


networks:
  cloudframework:
    driver: bridge

volumes:
  cf_data:
  mongodb:
  mongodb-express: