version: '3.4'
services:
  fe-nft: 
    image: yanivomc/fe-nft:latest
    container_name: fe-nft
    build: ./part-2-fe
    networks:
      - cloudframework
      - servicesnetwork
    depends_on:
      # - product-consumer
      # - rmq
      - mongo
    ports:
      - "80:8081"
    restart: always
#### fe sidecar (this is the prodoucer api)
  fe-sidecar-api: 
    image: yanivomc/fe-sidecar-api:latest
    build: ./part-2-sidecar/sidecar-producer
    network_mode: "container:fe-nft"
    networks:
     - cloudframework
     - servicesnetwork

    depends_on: 
      - fe-nft
    restart: always
  


############################
  # Mongodb state store
############################
  mongo:
    image: "mongo"
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=pass12345
    ports:
      - "27017:27017"
    networks:
      - cloudframework
    volumes:
      - mongodb:/data/db
    restart: always
############################
  # Mongodb express UI
############################
  mongo-express:
    image: mongo-express
    
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongo
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_ADMINUSERNAME=root
    - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
    - ME_CONFIG_BASICAUTH_USERNAME=admin
    - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
    - mongo
    networks:
    - cloudframework
    ports:
    - 9091:8081
    restart: always





volumes:
  cf_data:
  mongodb:
  mongodb-express:



  networks:
  cloudframework:
    driver: bridge
  servicesnetwork:
    name: servicesNetwork
    external: true