apiVersion: v1
kind: Service
metadata:
  name: bear-svc  
  labels:
    app: bear
spec:
  selector:
    app: bear
  ports: 
    - port: 80
      targetPort: 80
  type: ClusterIP
      
---

apiVersion: v1
kind: Service
metadata:
  name: moose-svc  
  labels:
    app: moose
spec:
  selector:
    app: moose
  ports: 
    - port: 80
      targetPort: 80
  type: ClusterIP
      
