kind: Service     
apiVersion: v1     
metadata:
  name: {{ .Release.Name }} #from RELEASE NAME
spec:
  selector:
    app: music    
  type: {{ .Values.service.lbtype | default .Values.default.lbtype | quote }}
  ports:         
  - name: http   
    protocol: TCP
    port: {{ .Values.service.port }} 
    targetPort: {{ .Values.service.targetport }} 
