apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bear
  name: bear
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bear
  type: ClusterIP
status:
  loadBalancer: {}
