apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bear
  name: bear
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bear
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bear
    spec:
      containers:
      - image: supergiantkir/animals:bear
        name: animals
        resources: {}
status: {}
