apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: moose
  name: moose
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moose
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: moose
    spec:
      containers:
      - image: supergiantkir/animals:moose
        name: animals
        resources: {}
status: {}
