apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    app: bear
    env: qa
spec:
  containers:
  - name: app1
    image: supergiantkir/animals:bear
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /storage
      name: test-volume
  - name: app2
    image: yanivomc/spring-music:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - mountPath: /storage
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /tmp/files
      