apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
spec:
  containers:
  - name: qos-demo-ctr
    image: yanivomc/spring-music:latest
    resources:
      limits:
        memory: "100Mi"
        cpu: "200m"
      requests:
        memory: "100Mi"
        cpu: "200m"
---
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-2
spec:
  containers:
  - name: qos-demo-2-ctr
    image: yanivomc/spring-music:latest
    resources:
      limits:
        memory: "100Mi"
      requests:
        memory: "50Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-3
  namespace: qos
spec:
  containers:
  - name: qos-demo-3-ctr
    image: yanivomc/spring-music:latest


