
apiVersion: v1
kind: Service
metadata:
  name: animal-svc  
  labels:
    app1: beer
    app2: moose
spec:
  selector:
    app: animal-app  
  ports: 
    - port: 80
      targetPort: 80
  type: LoadBalancer