
apiVersion: v1
kind: Service
metadata:
  name: animal-svc  
  labels:
    app: beer, moose
spec:
  selector:
    app: animal-app  
  ports: 
    - port: 80
      targetPort: 8080
  type: LoadBalancer