apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear
spec:
  replicas: 5
  selector:  
    matchLabels:
      app: bear
      type: animals
  template:
    metadata:
      labels:
        app: bear
        type: animals
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: system
                operator: In
                values: 
                  - linux
      containers:
      - name: bear
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moose
spec:
  replicas: 2
  selector:  
    matchLabels:
      type: animals
      app: moose
  template:
    metadata:
      labels:
        type: animals
        app: moose
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - moose
            topologyKey: topology.kubernetes.io/zone
      containers:
      - name: moose
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80

