apiVersion: apps/v1
kind: Deployment
metadata:
  name: moose
spec:
  replicas: 2
  selector:  
    matchLabels:
      type: animals
      app: moose
  template:
    metadata:
      labels:
        type: animals
        app: moose
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - moose
            topologyKey: topology.kubernetes.io/zone
      containers:
      - name: moose
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80

