apiVersion: v1
kind: Service
metadata:
  name: spring-music-service
  labels:
    app: spring-musicapp
spec:    
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: spring-svc
  selector:
    app: spring-musicapp