apiVersion: v1
kind: Pod
metadata:
  labels:
    name: springApp
spec:
  containers:
  - name: springApp
    image: yanivomc/spring-music:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
