apiVersion: v1
kind: Pod
metadata:
  name: burstable-pod
spec:
  containers:
    - name: burstable-container
      image: nginx:latest
      resources:
        limits:
          cpu: "100m"
          memory: "100Mi"
        requests:
          cpu: "50m"
          memory: "50Mi"
