apiVersion: v1
kind: Pod
metadata:
  name: guaranteed-pod
spec:
  containers:
    - name: guaranteed-container
      image: nginx:latest
      resources:
        limits:
          cpu: "100m"
          memory: "100Mi"
        requests:
          cpu: "100m"
          memory: "100Mi"
