apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-burstable
  namespace: pra 
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "100Mi"
        cpu: "300m"
