apiVersion: apps/v1
kind: Deployment
metadata:
  name: moose
spec:
  replicas: 2
  selector:  
    matchLabels:
      app: moose
      type: animals
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: moose
        type: animals
    spec:
      containers:
      - name: moose
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80

