database_prod: 
  dbname: db_mysql
  dbtable: music
database_test: 
  dbname: db_mysql-test
  dbtable: music
pods: 
  image: yanivomc/spring-music
  tag: latest
appName: spring-music
localserviceType: NodePort
ENV: local
serviceType: LoadBalancer
replicas: 1

food:
  drink: beer
  eat: Peanut Butter and Jelly Sandwich