# beer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beer
  template:
    metadata:
      labels:
        app: beer
        svc: moosebeer
    spec:
      containers:
      - name: beer
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80

---      
# moose-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moose-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moose
      svc: moosebeer
  template:
    metadata:
      labels:
        app: moose
        svc: moosebeer
    spec:
      containers:
      - name: moose
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80  