apiVersion: v1
kind: Service
metadata:
  labels:
    app: lab01
  name: lab01
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    lab: canary
  sessionAffinity: None
  type: LoadBalancer