
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bear-svc  
  labels:
    app: bear    
spec:
  selector:
    app: bear
  {{- if eq .Values.ingressEnables "no" }} 
    Type: {{ .Values.srvType }}
  {{- end }}
  ports: 
    - port: 80
      targetPort: 80
  type: ClusterIP
      
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-moose-svc  
  labels:
    app: moose
spec:
  selector:
    app: moose
  {{- if eq .Values.ingressEnables "no" }} 
    Type: {{ .Values.srvType }}
  {{- end }}
  ports: 
    - port: 80
      targetPort: 80
  type: ClusterIP
      
