apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
  labels:
    app: spring-music
spec:
  replicas: 2
  selector:  
    matchLabels:
      app: spring-music
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
      - name: spring-music
        image: yanivomc/spring-music:latest
        ports:
          - containerPort: 8080
---
kind: Service      # Create new service
apiVersion: v1     
metadata:
  name: spring-svc
  labels:
    app: spring-music
spec:
  selector:
    app: spring-music
  ports:          # Map incoming port to target port
    - port: 80
      targetPort: 8080
  type: NodePort

