version: '3'
services: 
  web: 
   build: .
   depends_on:
     - db_mysql     
   ports: 
     - 8080:8080
  #  volumes: 
  #      - ./artifactsa:/code
   networks:
     - app_layer
     - db_layer
  #  entrypoint:
  #    - java 
  #    - -jar 
  #    - -Dspring.profiles.active=mysql 
  #    - spring-music.jar
     
  
  db_mysql:
    image: wangxian/alpine-mysql
    environment: # env variables 
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=music
    ports:
      - 3302:3306
    networks:
      - db_layer



networks: # custom configuration per network defined
 db_layer:
  driver: bridge
 app_layer:
  driver: bridge
