apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-moose
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animals
  template:
    metadata:
      labels:
        app: animals
    spec:
      containers:
        - name: animals
          image: supergiantkir/animals:moose
          ports:
            - containerPort: 80
              protocol: TCP