# NOTE THAT THERE ARE ERRORS IN THE YAML FILE FOR YOU TO FIX
version: '3' # Docker-compose YAML version for docker compose builder

services:
  web:
    build: .
    depends_on:
      - db_mysql
    ports:
      - 8080:8080
    networks:
      - db_layer
      - app_layer

  db_mysql:
    image: wangxian/alpine-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=music
    ports:
      - 3302:3306
    networks:
      - db_layer

networks:
  db_layer:
    driver: bridge
  app_layer:
    driver: bridge
