apiVersion: apps/v1 # k8s API version which depends on kind
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    application: spring-music
    stage: qa
spec:
  selector:
    matchLabels:
      app: spring-music
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
      - name: spring-music
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080