apiVersion: v1 # k8s API version which depends on kind
kind: Pod
metadata:
  name: nginx
  labels:
    application: ngnix
spec:
  containers:
    - name: nginx
      image:  nginx:1.7.9
      resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      ports:
      - containerPort: 80
    - name: springapp
      image:  yanivomc/spring-music:latest
      resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      ports:
      - containerPort: 8080
#    env:
#      - name:  MIRIENV
#        value:  1.0