version: '3.8'

services:

  spring-app:
   image: -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=music yanivomc/spring-music:latest
   ports: 
     - 80:8080
   networks: 
     - fe-lan
   command: java -jar -Dspring.profiles.active=mysql spring-music.jar

  mysql-db:
   image: yanivomc/spring-mysql:latest
   networks: 
     - fe-lan

networks:
 db-lan:
 fe-lan:


