apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear-deployment
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0%
      maxSurge: 100%
  selector:
    matchLabels:
      app: bear-apps
  template:
    metadata:
      labels:
        app: bear-apps
        type: animal-apps
    spec:
      containers:
      - name: moose
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80