apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear-{{.Values.App.postfix}}
spec:
  replicas: {{.Values.App.replicas}}
  selector:
    matchLabels:
    {{- include "animal.data" . | nindent 6}}
  template:
    metadata:
      labels:
      {{- include "animal.data" . | nindent 8}}
    spec:
      containers:
        - name: bear
          image: supergiantkir/animals:bear
          ports:
            - containerPort: {{.Values.App.port}}
