version: '3.8'

services:

  spring-app:
   image: yanivomc/spring-music:latest
   ports: 
     - 80:8080
   networks: 
     - db-lan

  mysql-db:
   image: yanivomc/spring-mysql:latest
   networks: 
     - fe-lan

networks:
 db-lan:
 fe-lan:


