apiVersion: apps/v1
kind: Deployment
metadata:
  name: moose-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moose-apps
  template:
    metadata:
      labels:
        app: moose-apps
        type: animal-apps
    spec:
      containers:
      - name: moose
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80