apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.name}}-music
spec:
  selector: 
    matchLabels:
      app: music  
  replicas: {{.Values.appenv.replicas}}
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: {{.Values.appname}}
        image: {{.Values.appenv.image}}
        ports:
        - containerPort: 8080
