networks:
  db-lan:
  fe-lan:

version: '3.8'
services:
  spring-app:
    image: yanivomc/spring-music:latest
    ports:
      - 80:8080
    networks:
      - fe-lan
      - db-lan
    command: java -jar -Dspring.profiles.active=mysql spring-music.jar

  mysql_db:
    image: yanivomc/spring-mysql:latest
    networks:
      - db-lan
    container_name: mysql_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=music