apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}-{{.Chart.Version}}
  labels:
  {{- include "spring.labels" .}}
spec:
  selector: 
    matchLabels:
      {{- include "spring.labels" . | nindent 4}}
  replicas: {{.Values.replicas}}
  template:
    metadata:
      {{- include "spring.labels" . | nindent 4}}
    spec:
      containers:
      - name: {{.Values.appName}}
        image: {{.Values.pods.image}}
        ports:
        - containerPort: 8080

