apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: spring
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: app1
        image: supergiantkir/animals:bear
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        volumeMounts:
          - mountPath: "/storage"
            name: app-storage
        # ports:
        #   - containerPort: <Port>  
      - name:  app2
        image:  yanivomc/spring-music:latest
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        volumeMounts:
          - mountPath: "/storage"
            name: app-storage
      volumes:
        - name: app-storage
          hostPath:
            path:  "/tmp/files"
            type: DirectoryOrCreate
