apiVersion: apps/v1
kind: Deployment
metadata:
  name: moose-app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  replicas: 5
  selector:
    matchLabels:
      app: moose
      type: animal
  template:
    metadata:
      labels:
        app: moose
        type: animal
    spec:
      containers:
      - name: canary-moose
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80