apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-{{ .Values.release.cron_job_command_name }}
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}-{{ .Values.release.cron_job_command_name }}
            image: {{ .Values.release.cron_job_image }}:{{ .Values.release.cron_job_tag }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo {{ .Values.release.cron_job_command_name }} from the Kubernetes cluster
          restartPolicy: OnFailure