apiVersion: v1
kind: Service
metadata:
  name: animals-moose
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    svc_lb: animals
  sessionAffinity: None

