apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: fe  
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe-v1
  template:
    metadata:
      labels:
        app: fe-v1
    spec:
      containers:
      - name: redis
        image: redis:latest
        volumeMounts:
        - name: hostpathvolume
          mountPath: /storage
      - name: springapp
        image: yanivomc/spring-music:latest
        volumeMounts:
        - name: hostpathvolume
          mountPath: /sotrage
      volumes:
      - name: hostpathvolume
        hostPath:
          path: /data



