apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-moose
spec:
  replicas: 2
  selector:
    matchLabels:
      app: animals
  template:
    metadata:
      labels:
        app: animals
    spec:     
      podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: type
                operator: In
                values:
                - bear
            topologyKey: "system"
      podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: type
            operator: In
            values:
            - moose
        topologyKey: "kubernetes.io/hostname"
      containers:
        - name: animals
          image: supergiantkir/animals:moose
          ports:
            - containerPort: 80
              protocol: TCP