apiVersion: apps/v1 # K8S API Version
kind: Deployment  # Object Type
metadata: 
 name: bear-app
 labels:
  app: bear
  env: qa
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bear
  template:
    metadata:
       labels:
         app: bear
    spec:
      containers: 
      - name: bear
        image: supergiantkir/animals:bear
        ports: 
        - containerPort: 80
        volumeMounts:
          - mountPath: /storage
            name: app-storage
      - name: springapp
        image: yanivomc/spring-music:latest
        ports: 
        - containerPort: 8080
        volumeMounts:
          - mountPath: /storage
            name: app-storage
      volumes:
        - name: app-storage
          hostPath:
            # directory location on host
            path: /tmp/files
