apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: bear-app
 labels:
  app: bear
  env: qa
spec:
 containers: 
 - name: bear
   image: supergiantkir/animals:bear
   ports: 
   - containerPort: 80
