apiVersion: v1
kind: Pod
metadata:
  name: qos-guaranteed-pod-guarenteed
spec:
  containers:
    - name: bear
      image: supergiantkir/animals:bear
      resources:
        requests:
          memory: "200Mi"
          cpu: "700m"
        limits:          
          memory: 200Mi
          cpu: "700"
   

