---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
  namespace: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM-SHA-1"]
  users:
    - name: yanivomc-admin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: yanivomc-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdmin
          db: jb-platform
      scramCredentialsSecretName: my-scram
    - name: yanivomc
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: yanivomc-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdmin
          db: jb-platform
        - name: dbAdmin
          db: admin
        - name: readWrite
          db: admin
      scramCredentialsSecretName: my-scram

  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: yanivomc-password
# type: Opaque
# stringData:
#   password: xxxxxxx