pipeline {
    agent {
        docker {
            image 'python:3.10'
        }
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('docker-hub-creds')
        DOCKER_REGISTRY = 'ackermaster'
        REPO_NAME = 'fe-exam'  // Change to 'be-exam' for backend pipeline
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        
    }
    stages {
        
        stage('Clone Repository') {
            steps {
                git branch: 'workshop/argo-jenkins-exam', url: 'https://github.com/AckerMaster/devopshift-welcome.git'
            }
        }

        stage('Lint & Security Scan') {
            paralel{

                stage('Flake8 Linting'){
                    dir('exam-code/docker/fe/src'){
                        sh 'pip install flake8'
                        sh 'flake8 .'
                    }
                } 

                stage('Bandit Security Scan'){
                    dir('exam-code/docker/fe/src'){
                        sh 'pip install bandit'
                        sh 'bandit -r .'
                    }
                }           
            }
        }
        
    }

}