apiVersion: apps/v1
kind: Deployment
metadata:
  name: moose
spec:
  replicas: 1
  selector:  
    matchLabels:
      type: animals
      app: moose
  template:
    metadata:
      labels:
        type: animals
        app: moose
    spec:
      containers:
      - name: moose
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80
