apiVersion: apps/v1
kind: Deployment
metadata:
  name: moose-deploy
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 100
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: moose-app
  template:
    metadata:
      labels:
        app: moose-app
        svc_lb: animals
    spec:
      containers:
      - image: supergiantkir/animals:bear
        imagePullPolicy: Always
        name: moose
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always