version: '3.8'
networks:
  db-lan:
  fe-lan:
services:
  spring-app:
    image: yanivomc/spring-music:latest
    networks:
      - db-lan
      - fe-lan
    ports:
      - 80:8080
  mysql-db:
    image: yanivomc/spring-mysql:latest
    networks:
      - db-lan