apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear-deployment
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: bear
      type: animals
  template:
    metadata:
      labels:
        app: bear
        type: animals
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
          - key: node.kubernetes.io/os
            operator: In
            values:
            - linux
      containers:
      - name: bear-app
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80