kind: Service      # Create new service
apiVersion: v1     
metadata:
  name: svc-animals # Name of the service
spec:
  selector:
    type: animals 
  ports:          # Map incoming port to target port
  - name: animals
    protocol: TCP
    port: 80
    targetPort: 80   

  type: LoadBalancer 
