apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear
spec:
  replicas: 1
  selector:  
    matchLabels:
      app: bear
      type: animals
  template:
    metadata:
      labels:
        app: bear
        type: animals
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: system
                operator: In
                values: 
                  - linux
      containers:
      - name: bear
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
