apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-music
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
      - image: yanivomc/spring-music:latest
        imagePullPolicy: Always
        name: spring-music-container
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-music
  sessionAffinity: None
  type: NodePort