apiVersion: v1
kind: Pod
metadata:
  name: bear
  labels:
    app: bear
    env: qa
spec:
  containers:
  - name: bear-container
    image: supergiantkir/animals:bear
    ports:
    - containerPort: 80