apiVersion: apps/v1
kind: Deployment
metadata:
  name: hezi-animals-moose-deployment
  labels:
    app: animals-moose
spec:
  replicas: 2
  selector:
    matchLabels:
      app-svc: animals-app
      app: animals-moose
  template:
    metadata:
      labels:
        app-svc: animals-app
        app: animals-moose
    spec:
      containers:
      - name: moose
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - animals-bear
            topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - animals-moose
            topologyKey: kubernetes.io/hostname