apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2 
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
