apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: quickstart
  namespace: default
spec:
  type: filebeat
  version: 8.16.0
  kibanaRef:
    name: quickstart
  elasticsearchRef:
    name: quickstart
  config:
    logging.level: debug
    setup.dashboards.enabled: false
    filebeat.inputs:
    - type: container
      paths:
      - /var/log/containers/fe-deployment*_fefaker*.log
      json.keys_under_root: true
      json.add_error_key: true
    output.elasticsearch:
      hosts: ["http://quickstart-es-http.default.svc.cluster.local:9200"]
      indices:
        - index: "filebeat-fe-%{[agent.version]}-%{+yyyy.MM.dd}"
  daemonSet:
    podTemplate:
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        securityContext:
          runAsUser: 0
        containers:
        - name: filebeat
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
