apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: default
spec:
  version: 8.16.0
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    server.host: "0.0.0.0"
    server.basePath: "/kibana"  # Makes Kibana available under /kibana
    server.rewriteBasePath: true  # Rewrites URLs to use /kibana
    elasticsearch.hosts: ["https://quickstart-es-http.default.svc.cluster.local:9200"]  # Use HTTPS for the Elasticsearch host
    elasticsearch.ssl.verificationMode: "none"  # Disable SSL verification for self-signed certificates

  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: ClusterIP

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kibana-httproute
  namespace: default  
spec:
  parentRefs:
    - name: global-gateway  # Make sure this matches your defined Gateway resource
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /kibana
      backendRefs:
        - name: quickstart-kb-http  # The name of the Kibana service created by ECK. Usually, it's "<kibana-name>-kb-http"
          port: 5601                # Default Kibana port
