apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: default
spec:
  version: 8.2.0
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://quickstart-es-http.default.svc.cluster.local:9200"]
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: ClusterIP

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kibana-httproute
  namespace: default  
spec:
  parentRefs:
    - name: global-gateway  # Make sure this matches your defined Gateway resource
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /kibana
      backendRefs:
        - name: quickstart-kb-http  # The name of the Kibana service created by ECK. Usually, it's "<kibana-name>-kb-http"
          port: 5601                # Default Kibana port
