apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: metricbeat
  namespace: default
spec:
  type: metricbeat
  version: 8.16.0
  elasticsearchRef:
    name: quickstart
  kibanaRef:
    name: quickstart
  config:
    setup.kibana:
      host: "http://quickstart-kb-http.default.svc:5601/kibana"  # Changed to HTTPS
      ssl.verification_mode: "none"  # Disable SSL verification for self-signed certificates
    setup.dashboards:
      enabled: true
      directory: /usr/share/metricbeat/kibana
    output.elasticsearch:
      hosts: ["https://quickstart-es-http.default.svc.cluster.local:9200"]  # Changed to HTTPS
      ssl:
        verification_mode: "none"  # Disable SSL verification for self-signed certificates
    metricbeat:
      autodiscover:
        providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
      modules:
      - module: system
        period: 10s
        metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
        processes:
        - .*
      - module: system
        period: 1m
        metricsets:
        - filesystem
        - fsstat
        processors:
        - drop_event:
            when:
              regexp:
                system.filesystem.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib)($|/)
        extras:
          system.hostfs: /hostfs
      - module: kubernetes
        metricsets:
        - node
        - system
        - pod
        - container
        - volume
        period: 10s
        hosts:
        - https://${HOST_IP}:10250
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        ssl.verification_mode: "none"  # Ensure that Metricbeat doesn’t fail on verification
      - module: kubernetes
        metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_statefulset
        - state_pod
        - state_container
        period: 10s
        hosts:
        - http://kube-state-metrics.kube-system.svc.cluster.local:8080
    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: metricbeat
        automountServiceAccountToken: true
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        terminationGracePeriodSeconds: 30
        containers:
        - name: metricbeat
          args:
          - -e
          - -c
          - /etc/beat.yml
          - -system.hostfs=/hostfs
          env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: proc
            mountPath: /hostfs/proc
          - name: cgroup
            mountPath: /hostfs/sys/fs/cgroup
          - name: dockersock
            mountPath: /var/run/docker.sock
        volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
