apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat
rules:
- apiGroups: [""]
  resources:
  - pods
  - nodes
  - nodes/stats
  - namespaces
  - events
  - persistentvolumeclaims
  - persistentvolumes
  - services
  - endpoints
  - configmaps
  - limitranges
  - resourcequotas
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - daemonsets
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["policy"]
  resources:
  - poddisruptionbudgets
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - networkpolicies
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["monitoring.coreos.com"]
  resources:
  - prometheusrules
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricbeat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metricbeat
subjects:
- kind: ServiceAccount
  name: metricbeat
  namespace: default
---
# apiVersion: beat.k8s.elastic.co/v1beta1
# kind: Beat
# metadata:
#   name: metricbeat
#   namespace: default
# spec:
#   type: metricbeat
#   version: 8.2.0
#   elasticsearchRef:
#     name: quickstart
#   kibanaRef:
#     name: quickstart
#   config:
#     metricbeat.modules:
#     - module: kubernetes
#       metricsets:
#         - node
#         - system
#         - pod
#         - container
#         - volume
#         - cluster
#       period: 10s
#       host: "${NODE_NAME}"
#       hosts: ["https://${NODE_NAME}:10250"]
#       bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
#       ssl.verification_mode: "none"
#     - module: kubernetes
#       metricsets:
#         - state_node
#         - state_deployment
#         - state_replicaset
#         - state_statefulset
#         - state_pod
#         - state_container
#       period: 10s
#       hosts: ["kube-state-metrics:8080"]
#   daemonSet:
#     podTemplate:
#       spec:
#         serviceAccountName: metricbeat
#         containers:
#         - name: metricbeat
#           securityContext:
#             runAsUser: 0
#           volumeMounts:
#           - name: varlibdockercontainers
#             mountPath: /var/lib/docker/containers
#           - name: varrunc
#             mountPath: /var/run
#         volumes:
#         - name: varlibdockercontainers
#           hostPath:
#             path: /var/lib/docker/containers
#         - name: varrunc
#           hostPath:
#             path: /var/run
