apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-kubernetes-operator
  # namespace: mongodb
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-kubernetes-operator-rolebinding
  # namespace: mongodb
subjects:
- kind: ServiceAccount
  name: mongodb-kubernetes-operator
  namespace: mongodb
roleRef:
  kind: Role
  name: mongodb-operator-role
  apiGroup: rbac.authorization.k8s.io
