apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  dbname: {{ .Values.database_test.dbname | upper}}
  dbtable: {{ .Values.database_test.dbtable | upper}}
  image: {{ .Values.pods.image }}:{{ .Values.pods.tag }}
