version: '3.9'
services:
  spring-app:
    image: yanivomc/spring-music:latest
    ports:
      - 80:8080
      - 90:8080
    networks:
      - mylan-network

  mysql_db:
    image: yanivomc/spring-mysql:latest
    container_name: mysql_db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=music
    ports:
      - 3306:3306
    networks:
      - mylan-network


networks:
  mylan-network:


