apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spring-music 
spec:
  selector: 
    matchLabels:
      app: music  
  replicas: {{ .Values.release.replicas }}
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name:  {{ .Values.release.name }}
        image: {{ .Values.release.image }}:{{ .Values.release.tag }}
        ports:
        - containerPort: {{ .Values.release.targetPort }}
