apiVersion: apps/v1
kind: Deployment
metadata:
  name: bear
spec:
  replicas: 2
  selector:
    matchLabels:
      app: animals
      animal: bear
  template:
    metadata:
      labels:
        app: animals
        animal: bear
    spec:
      containers:
        - name: bear
          image: supergiantkir/animals:bear
          ports:
            - containerPort: 80
